### ISSUE TITLE
Can't build in Android Studio

### ISSUE THREAD

**Issue by Viish** [YiXiYeah/react-native-linphone#1]
Could not read script '/home/sberfini/Work/react-native-linphone/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' as it does not exist.

**Comment by Viish** [comment]
Nevermind I got it to work, was missing 'npm install" step.

**Comment by nn444249983** [comment]
I try it, I use AndroidQ



| |
cnlovefj
邮箱：cnlovefj@163.com
|

Signature is customized by Netease Mail Master

On 06/30/2020 19:47, Sylvain Berfini wrote:

Could not read script '/home/sberfini/Work/react-native-linphone/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' as it does not exist.

**Comment by YiXiYeah** [comment]
Hi,
I click "123131" to start the service, an exception occurs.
Whether it is a problem with the react native project path, I use Android studio to create a new project can run, react native project does not work.
